### ISSUE TITLE
installation failed on macOS Monterey 12.6.2

### ISSUE THREAD

**Issue by shanrongzhang** [yu02019/MouseGAN-pp#2]
installation failed on macOS Monterey 12.6.2. 

conda env create -f environment.yml

Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - freetype==2.10.2=hd328e21_0
  - jpeg==9b=hb83a4c4_2
  - mkl_fft==1.2.0=py36h45dec08_0
  - vc==14.1=h0510ff6_4
  - pyyaml==5.3.1=py36he774522_1
  - setuptools==50.3.0=py36h9490d1a_1
  - libpng==1.6.37=h2a8f88b_0
  - numpy-base==1.19.1=py36ha3acd2a_0
  - statsmodels==0.12.2=py36h2bbff1b_0
  - ca-certificates==2021.10.26=haa95532_2
  - scipy==1.5.2=py36h9439919_0
  - lz4-c==1.9.2=hf4a77e7_3
  - matplotlib-base==3.3.1=py36hba9282a_0
  - cudatoolkit==10.1.243=h74a9793_0
  - yaml==0.2.5=he774522_0
  - wincertstore==0.2=py36h7fe50ca_0
  - openssl==1.1.1l=h2bbff1b_0
  - zlib==1.2.11=h62dcd97_4
  - icc_rt==2019.0.0=h0cc432a_1
  - tornado==6.0.4=py36he774522_1
  - cytoolz==0.11.0=py36he774522_0
  - python==3.6.12=h5500b2f_2
  - sip==4.19.8=py36h6538335_0
  - intel-openmp==2020.2=254
  - torchvision==0.4.2=py36_cu101
  - zstd==1.4.5=h04227a9_0
  - vs2015_runtime==14.16.27012=hf0eaf9b_3
  - ninja==1.10.1=py36h7ef1ec2_0
  - mkl-service==2.3.0=py36hb782905_0
  - mkl==2020.2=256
  - pywavelets==1.1.1=py36he774522_2
  - sqlite==3.33.0=h2a8f88b_0
  - tk==8.6.10=he774522_0
  - pyqt==5.9.2=py36h6538335_2
  - icu==58.2=ha925a31_3
  - libtiff==4.1.0=h56a325e_1
  - mkl_random==1.1.1=py36h47e9c7a_0
  - pandas==1.1.5=py36hd77b12b_0
  - pytorch==1.3.1=py3.6_cuda101_cudnn7_0
  - kiwisolver==1.2.0=py36h74a9793_0
  - qt==5.9.7=vc14h73c81de_0
  - xz==5.2.5=h62dcd97_0

**Comment by yu02019** [comment]
I just uploaded a new yml file without build numbers

Maybe you can use the following command to install the environment:
`
conda env create -f environment--no-builds.yml
`
Some packages may have different version number at different OS
(refer to this [question](https://stackoverflow.com/questions/49154899/resolvepackagenotfound-create-env-using-conda-and-yml-file-on-macos))

Besides, I have run and tested our methods on Windows10 and Linux (just like [colab notebook](https://colab.research.google.com/drive/1IqWeyO7eLb0phOkUnBEuD4bD5napD-k-?usp=sharing)). However, if you want to train our model, it is not recommended to use Mac (as it doesn't have NVIDIA GPU to accelerate).

**Comment by shanrongzhang** [comment]
Thank you =for quick reply. I will test you mouseGAN++ on Windows10. Best wishes,

**Comment by yu02019** [comment]
Thank you for your interest. If you have any problems, feel free to open an issue.

**Comment by shanrongzhang** [comment]
I tried your no-build version. There were less fails. But, it failed again on MacOS. So, I'd better use Windows10 or Linux. Thank you in the same manor! 

Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - cudatoolkit=10.1.243
  - wincertstore=0.2
  - vs2015_runtime=14.16.27012
  - icc_rt=2019.0.0
  - vc=14.1
